# Generated by Django 3.0.6 on 2020-05-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('funding', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Startups',
            },
        ),
    ]
