# Generated by Django 3.0.2 on 2020-05-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
