# Generated by Django 3.0.6 on 2020-07-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_startup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
