# Generated by Django 3.0.6 on 2020-07-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_auto_20200721_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='address',
            field=models.CharField(default='P.O BOX 4050 Nairobi', max_length=200),
        ),
        migrations.AddField(
            model_name='startup',
            name='category',
            field=models.CharField(choices=[('science', 'science'), ('Technology', 'Technology'), ('Agriculture', 'Agriculture'), ('Energy & Petroleum', 'Energy & petroleum'), ('Industrial', 'Industrial'), ('space', 'Space'), ('Health', 'Health'), ('Tourism', 'Tourism')], default='Technology', max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='email',
            field=models.EmailField(default='startup@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='startup',
            name='funding_reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='phone_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='website',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Descriptions',
        ),
    ]
