# Generated by Django 3.0.6 on 2020-07-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0005_auto_20200722_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='id',
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
