# Generated by Django 3.0.6 on 2020-07-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_auto_20200725_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
