# Generated by Django 3.0.6 on 2020-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_auto_20200725_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
